countries = {
 'cameroon.olx.com': 'Cameroon',
 'htindia.olx.in': 'HTIndia',
 'secondlife.olx.com': 'Second Life',
 'unknown': 'Unknown',
 'haibao.com.tw': 'Taiwan',
 'haibao.hk': 'HongKong',
 'haibao8.com': 'China',
 'jaovat.com': 'Vietnam',
 'olx-nederland.com': 'Netherlands',
 'olx.ae': 'United Arab Emirates',
 'olx.at': 'Austria',
 'olx.aw': 'Aruba',
 'olx.ba': 'Bosnia and Herzegovina',
 'olx.be': 'Belgium',
 'olx.bg': 'Bulgaria',
 'olx.bs': 'Bahamas',
 'olx.by': 'Belarus',
 'olx.bz': 'Belize',
 'olx.ca': 'Canada',
 'olx.ch': 'Switzerland',
 'olx.cl': 'Chile',
 'olx.co.ao': 'Angola',
 'olx.co.bw': 'Botswana',
 'olx.co.cr': 'Costa Rica',
 'olx.co.id': 'Indonesia',
 'olx.co.il': 'Israel',
 'olx.co.ke': 'Kenya',
 'olx.co.kr': 'South Korea',
 'olx.co.mz': 'Mozambique',
 'olx.co.nz': 'NewZealand',
 'olx.co.tz': 'Tanzania',
 'olx.co.ug': 'Uganda',
 'olx.co.uk': 'United Kingdom',
 'olx.co.za': 'SouthAfrica',
 'olx.com': 'United States',
 'olx.com.ar': 'Argentina',
 'olx.com.au': 'Australia',
 'olx.com.bd': 'Bangladesh',
 'olx.com.bo': 'Bolivia',
 'olx.com.br': 'Brazil',
 'olx.com.co': 'Colombia',
 'olx.com.cy': 'Cyprus',
 'olx.com.do': 'Dominican Republic',
 'olx.com.ec': 'Ecuador',
 'olx.com.eg': 'Egypt',
 'olx.com.gh': 'Ghana',
 'olx.com.gt': 'Guatemala',
 'olx.com.hr': 'Croatia',
 'olx.com.jm': 'Jamaica',
 'olx.com.mt': 'Malta',
 'olx.com.mx': 'Mexico',
 'olx.com.my': 'Malaysia',
 'olx.com.ng': 'Nigeria',
 'olx.com.ni': 'Nicaragua',
 'olx.com.pa': 'Panama',
 'olx.com.pe': 'Peru',
 'olx.com.ph': 'Philippines',
 'olx.com.pk': 'Pakistan',
 'olx.com.pr': 'Puerto Rico',
 'olx.com.py': 'Paraguay',
 'olx.com.sg': 'Singapore',
 'olx.com.sv': 'El Salvador',
 'olx.com.tr': 'Turkey',
 'olx.com.tt': 'Trinidad and Tobago',
 'olx.com.ua': 'Ukraine',
 'olx.com.uy': 'Uruguay',
 'olx.com.ve': 'Venezuela',
 'olx.cz': 'Czech Republic',
 'olx.de': 'Germany',
 'olx.dk': 'Denmark',
 'olx.dm': 'Dominica',
 'olx.ee': 'Estonia',
 'olx.es': 'Spain',
 'olx.fi': 'Finland',
 'olx.fr': 'France',
 'olx.gd': 'Grenada',
 'olx.gr': 'Greece',
 'olx.hn': 'Honduras',
 'olx.ht': 'Haiti',
 'olx.hu': 'Hungary',
 'olx.ie': 'Ireland',
 'olx.in': 'India',
 'olx.is': 'Iceland',
 'olx.it': 'Italy',
 'olx.jo': 'Jordan',
 'olx.jp': 'Japan',
 'olx.kz': 'Kazakhstan',
 'olx.li': 'Liechtenstein',
 'olx.lk': 'Sri Lanka',
 'olx.lt': 'Lithuania',
 'olx.lu': 'Luxembourg',
 'olx.lv': 'Latvia',
 'olx.ma': 'Morocco',
 'olx.md': 'Moldova',
 'olx.mu': 'Mauritius',
 'olx.no': 'Norway',
 'olx.pl': 'Poland',
 'olx.pt': 'Portugal',
 'olx.ro': 'Romania',
 'olx.rs': 'Serbia',
 'olx.ru': 'Rusia',
 'olx.se': 'Sweden',
 'olx.si': 'Slovenia',
 'olx.sk': 'Slovak Republic',
 'olx.tc': 'Turks and Caicos Islands',
 'olxalgerie.com': 'Algeria',
 'olxmonaco.com': 'Monaco',
 'olxthailand.com': 'Thailand',
 'olxtunisie.com': 'Tunisia',
 'zimbabwe.olx.com': 'Zimbabwe'
}

ordered_countries = [
 'unknown',
 'olx.com',
 'olx.com.ar',
 'olxalgerie.com',
 'olx.co.ao',
 'olx.aw',
 'olx.com.au',
 'olx.at',
 'olx.bs',
 'olx.com.bd',
 'olx.by',
 'olx.be',
 'olx.bz',
 'olx.com.bo',
 'olx.ba',
 'olx.co.bw',
 'olx.com.br',
 'olx.bg',
 'cameroon.olx.com',
 'olx.ca',
 'olx.cl',
 'haibao8.com',
 'olx.com.co',
 'olx.co.cr',
 'olx.com.hr',
 'olx.com.cy',
 'olx.cz',
 'olx.dk',
 'olx.dm',
 'olx.com.do',
 'olx.com.ec',
 'olx.com.eg',
 'olx.com.sv',
 'olx.ee',
 'olx.fi',
 'olx.fr',
 'olx.de',
 'olx.com.gh',
 'olx.gr',
 'olx.gd',
 'olx.com.gt',
 'olx.ht',
 'olx.hn',
 'haibao.hk',
 'olx.hu',
 'olx.is',
 'olx.in',
 'olx.co.id',
 'olx.ie',
 'olx.co.il',
 'olx.it',
 'olx.com.jm',
 'olx.jp',
 'olx.jo',
 'olx.kz',
 'olx.co.ke',
 'olx.co.kr',
 'olx.lv',
 'olx.li',
 'olx.lt',
 'olx.lu',
 'olx.com.my',
 'olx.com.mt',
 'olx.mu',
 'olx.com.mx',
 'olx.md',
 'olxmonaco.com',
 'olx.ma',
 'olx.co.mz',
 'olx-nederland.com',
 'olx.co.nz',
 'olx.com.ni',
 'olx.com.ng',
 'olx.no',
 'olx.com.pk',
 'olx.com.pa',
 'olx.com.py',
 'olx.com.pe',
 'olx.com.ph',
 'olx.pl',
 'olx.pt',
 'olx.com.pr',
 'olx.ro',
 'olx.ru',
 'olx.com.sg',
 'olx.sk',
 'olx.si',
 'olx.co.za',
 'olx.es',
 'olx.lk',
 'olx.se',
 'olx.ch',
 'haibao.com.tw',
 'olx.co.tz',
 'olxthailand.com',
 'olx.com.tt',
 'olxtunisie.com',
 'olx.com.tr',
 'olx.tc',
 'olx.co.ug',
 'olx.com.ua',
 'olx.ae',
 'olx.com.uy',
 'olx.com.ve',
 'zimbabwe.olx.com',
 'olx.co.uk',
 'secondlife.olx.com',
 'jaovat.com',
 'olx.rs',
 'htindia.olx.in'
]
